### ISSUE TITLE
How to set resource type for jpa entity?

### ISSUE THREAD

**Issue by exports** [katharsis-project/katharsis-framework#416]
I try to set the resource type for a jpa entity with `@JsonApiResource` in katharsis-jpa, but it does not work.

**Comment by loickR** [comment]
I've the same problem, when I declare my entities with @JsonApiResource annotation, it seems katharsis ignore them or does not apply mapping type specified. 
The github "spring-boot-examples" repository show an example to implement a specific JpaMapper in order to have two classes : one for the entity (with @Entity annotation) and the other with a DTO (with @JsonApiResource).
This solution works but I'm looking for another easier solution to have my entities with the @JsonApiResource, because without the jpa module the annotation worked fine. 

Did anyone get an idea on it ?

**Comment by exports** [comment]
@loickR Is your mapped entity approach works fine? I cannot create new resource when use mapped entity, and the validation module is broken, so I have to patch the whole module to make it work.

**Comment by loickR** [comment]
I think so but currently, I've three classes my entity User (with @Entity and @JsonApiResource), my repository and my JpaConfig class implementing the SpringTransactionRunner bean and the JpaModule (like the example on github). Here the code of my classes 

```
@JsonApiResource(type = "users")
@Entity
@Table (name = "users")
@EqualsAndHashCode(of = "firstName")
@NoArgsConstructor
public class User {

    @Getter
    @Setter
    @JsonApiId
    @Id
    @GeneratedValue (strategy = GenerationType.AUTO)
    private Long id;

    @Getter
    @Setter
    @Column
    @JsonProperty (value = "last-name")
    private String lastName;

    @Getter
    @Setter
    @Column
    @JsonProperty (value = "first-name")
    private String firstName;
}
```
```
@Component
public class UserResourceRepository extends JpaEntityRepository<User, Long>  {

    @Autowired
    public UserResourceRepository(JpaModule module) {
        super(module, module.getRepositoryConfig(User.class));
    } 
}
```
```
@Configuration
public class JpaConfig {

    @Autowired
    private EntityManager em;

    @Autowired
    private TransactionRunner transactionRunner;

    @Bean
    public SpringTransactionRunner transactionRunner() {
        return new SpringTransactionRunner();
    }

    @Bean
    public JpaModule jpaModule() {
       final JpaModule module = JpaModule.newServerModule(em, transactionRunner);
       return module;
    }
}
```
```
katharsis:
  resourcePackage: com.my_package
  domainName: http://localhost:8080
  pathPrefix: /api
  jpa:
    enabled: false

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_db
    username: user
    password: user_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
```
